# Generated by Django 4.2.7 on 2026-01-30 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='dealers/avatars/', verbose_name='عکس')),
                ('bio', models.TextField(blank=True, verbose_name='درباره')),
                ('whatsapp_number', models.CharField(blank=True, max_length=11, verbose_name='واتساپ')),
                ('show_phone', models.BooleanField(default=True, verbose_name='نمایش شماره')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='امتیاز')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فروشنده',
                'verbose_name_plural': 'فروشندگان',
                'ordering': ['-rating', '-total_sales'],
            },
        ),
        migrations.CreateModel(
            name='DealerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='امتیاز')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dealers.dealerprofile', verbose_name='فروشنده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'unique_together': {('dealer', 'user')},
            },
        ),
    ]
