# Generated by Django 4.2.7 on 2026-01-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='برند')),
                ('model', models.CharField(max_length=100, verbose_name='مدل')),
                ('year', models.PositiveIntegerField(verbose_name='سال ساخت')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت (تومان)')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('engine_capacity', models.CharField(blank=True, max_length=20, verbose_name='حجم موتور')),
                ('fuel_type', models.CharField(choices=[('petrol', 'بنزین'), ('diesel', 'گازوئیل'), ('hybrid', 'هیبرید'), ('electric', 'برقی')], default='petrol', max_length=20, verbose_name='نوع سوخت')),
                ('transmission', models.CharField(choices=[('manual', 'دستی'), ('automatic', 'اتوماتیک')], default='manual', max_length=20, verbose_name='گیربکس')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='کارکرد (کیلومتر)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'خودرو',
                'verbose_name_plural': 'خودروها',
                'ordering': ['-created_at'],
            },
        ),
    ]
