# Generated by Django 4.2.7 on 2026-01-30 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('phone', models.CharField(max_length=11, verbose_name='موبایل')),
                ('source', models.CharField(default='website', max_length=20, verbose_name='منبع')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شده'), ('interested', 'علاقه\u200cمند'), ('test_drive', 'تست درایو'), ('negotiating', 'در حال مذاکره'), ('closed_won', 'فروخته شد'), ('closed_lost', 'از دست رفت')], default='new', max_length=20, verbose_name='وضعیت')),
                ('budget_min', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداقل بودجه')),
                ('budget_max', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداکثر بودجه')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سرنخ',
                'verbose_name_plural': 'سرنخ\u200cها',
            },
        ),
    ]
