# Generated by Django 4.2.7 on 2026-01-30 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('push', 'پوش نوتیفیکیشن'), ('sms', 'پیامک'), ('whatsapp', 'واتساپ'), ('email', 'ایمیل')], max_length=20, verbose_name='کانال')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن')),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('sent', 'ارسال شد'), ('failed', 'ناموفق'), ('delivered', 'تحویل داده شد')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('error_message', models.TextField(blank=True, verbose_name='خطا')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('clicked', models.BooleanField(default=False, verbose_name='کلیک شده')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان کلیک')),
            ],
            options={
                'verbose_name': 'لاگ اعلان',
                'verbose_name_plural': 'لاگ اعلان\u200cها',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=500, verbose_name='توکن دستگاه')),
                ('device_type', models.CharField(choices=[('android', 'اندروید'), ('ios', 'iOS'), ('web', 'وب')], max_length=20, verbose_name='نوع دستگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='آخرین استفاده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دستگاه',
                'verbose_name_plural': 'دستگاه\u200cها',
                'unique_together': {('user', 'device_token')},
            },
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'کمپین', 'verbose_name_plural': 'کمپین\u200cها'},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='is_active',
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='link',
            field=models.URLField(blank=True, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='نام کمپین'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='radius_km',
            field=models.PositiveIntegerField(default=5, verbose_name='شعاع (کیلومتر)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_push',
            field=models.BooleanField(default=True, verbose_name='ارسال پوش'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='ارسال پیامک'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_whatsapp',
            field=models.BooleanField(default=False, verbose_name='ارسال واتساپ'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('paused', 'متوقف'), ('completed', 'تمام شده')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی هدف'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی هدف'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('location', 'بر اساس موقعیت'), ('birthday', 'تبریک تولد'), ('manual', 'دستی'), ('scheduled', 'زمان\u200cبندی شده')], max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='message',
            field=models.TextField(verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_notifications.campaign', verbose_name='کمپین'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
