# Generated by Django 4.2.7 on 2026-01-30 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان سئو')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('excerpt', models.TextField(verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('featured_image', models.ImageField(upload_to='articles/', verbose_name='تصویر')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at'],
            },
        ),
    ]
